
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Invoice, Contract, Client, Billboard, MaintenanceLog, PrintingJob, Expense } from '../types';
import { getCompanyProfile, getCompanyLogo } from './mockData';
import { toast } from '../components/Toast';

// Colors
const COLOR_PRIMARY = [15, 23, 42]; // Slate 900
const COLOR_ACCENT = [249, 115, 22]; // Orange 500
const COLOR_TEXT = [51, 65, 85]; // Slate 700
const COLOR_TEXT_LIGHT = [100, 116, 139]; // Slate 500

export interface PdfBase64 { filename: string; base64: string; }
export interface PdfOutputOptions { asBase64?: boolean; }

// Either saves the PDF locally (default) or returns it as base64 for upload.
// Keeping both paths in one helper avoids leaking save-vs-email logic into
// every generator.
const finalizePdf = (doc: jsPDF, filename: string, options?: PdfOutputOptions): PdfBase64 | void => {
    if (options?.asBase64) {
        const dataUri = doc.output('datauristring');
        const base64 = dataUri.includes(';base64,') ? dataUri.split(';base64,')[1] : dataUri;
        return { filename, base64 };
    }
    doc.save(filename);
};

// Helper to safely execute autoTable regardless of import structure
const runAutoTable = (doc: any, options: any) => {
    try {
        if (typeof autoTable === 'function') {
            autoTable(doc, options);
            return;
        } 
        if (typeof (doc as any).autoTable === 'function') {
            (doc as any).autoTable(options);
            return;
        }
        if ((autoTable as any)?.default && typeof (autoTable as any).default === 'function') {
            (autoTable as any).default(doc, options);
            return;
        }
    } catch (e) {
        console.error('Error running autoTable:', e);
    }
};

const addCompanyHeader = (doc: jsPDF): number => {
    const profile = getCompanyProfile(); 
    const logo = getCompanyLogo();
    const pageWidth = doc.internal.pageSize.width;
    
    // Top Bar Background
    doc.setFillColor(COLOR_PRIMARY[0], COLOR_PRIMARY[1], COLOR_PRIMARY[2]);
    doc.rect(0, 0, pageWidth, 40, 'F');

    // Logo (White circle bg for contrast if needed, or just image)
    if (logo && logo.startsWith('data:image')) {
        try {
            doc.addImage(logo, 'JPEG', 14, 8, 24, 24);
        } catch (e) {
            try { doc.addImage(logo, 'PNG', 14, 8, 24, 24); } catch (err) {}
        }
    }

    // Company Name
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(255, 255, 255);
    doc.text(profile.name, 45, 18);

    // Accent line under name
    doc.setDrawColor(COLOR_ACCENT[0], COLOR_ACCENT[1], COLOR_ACCENT[2]);
    doc.setLineWidth(0.5);
    doc.line(45, 22, 100, 22);

    // Contact Details
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(200, 200, 200);
    
    const rightX = pageWidth - 14;
    let y = 14;
    doc.text(profile.address, rightX, y, { align: 'right' }); y += 5;
    doc.text(`${profile.city}, ${profile.country}`, rightX, y, { align: 'right' }); y += 5;
    doc.text(profile.phone, rightX, y, { align: 'right' }); y += 5;
    doc.text(profile.email, rightX, y, { align: 'right' }); y += 5;
    if(profile.vatNumber) doc.text(`VAT: ${profile.vatNumber}`, rightX, y, { align: 'right' });

    return 55; // Start content lower
};

const addFooter = (doc: jsPDF, pageNumber: number, overrideText?: string) => {
    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;
    const currentDate = new Date().toLocaleDateString();
    
    doc.setDrawColor(230);
    doc.line(14, pageHeight - 20, pageWidth - 14, pageHeight - 20);
    
    doc.setFontSize(8);
    doc.setTextColor(150);
    const text = overrideText || `Generated by Black Ivy Media System - ${currentDate}`;
    doc.text(text, 14, pageHeight - 12);
    doc.text(`Page ${pageNumber}`, pageWidth - 14, pageHeight - 12, { align: 'right' });
};

// --- Report Generators ---

// 1. Profit & Analytics Report
export const generateProfitAnalyticsPDF = (
    trends: any[], 
    expenseBreakdown: any[], 
    totals: { revenue: number, expenses: number, profit: number, margin: number }
) => {
    try {
        const doc = new jsPDF();
        let currentY = addCompanyHeader(doc);

        doc.setFontSize(22);
        doc.setTextColor(COLOR_PRIMARY[0], COLOR_PRIMARY[1], COLOR_PRIMARY[2]);
        doc.setFont("helvetica", "bold");
        doc.text('PROFIT & ANALYTICS REPORT', 14, currentY);
        
        currentY += 8;
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(COLOR_TEXT_LIGHT[0], COLOR_TEXT_LIGHT[1], COLOR_TEXT_LIGHT[2]);
        doc.text(`Generated: ${new Date().toLocaleDateString()}`, 14, currentY);
        
        currentY += 15;

        // Executive Summary Box
        doc.setFillColor(248, 250, 252);
        doc.roundedRect(14, currentY, 182, 35, 2, 2, 'F');
        doc.setDrawColor(226, 232, 240);
        doc.rect(14, currentY, 182, 35, 'S');

        doc.setFontSize(12);
        doc.setTextColor(COLOR_TEXT[0], COLOR_TEXT[1], COLOR_TEXT[2]);
        doc.setFont("helvetica", "bold");
        doc.text("Executive Financial Summary", 20, currentY + 8);

        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        
        // Row 1
        doc.text("Total Revenue", 20, currentY + 18);
        doc.text(`$${totals.revenue.toLocaleString()}`, 80, currentY + 18, { align: 'right' });
        
        doc.text("Total Expenses", 110, currentY + 18);
        doc.text(`$${totals.expenses.toLocaleString()}`, 170, currentY + 18, { align: 'right' });

        // Row 2
        doc.setFont("helvetica", "bold");
        doc.text("Net Profit", 20, currentY + 28);
        doc.setTextColor(totals.profit >= 0 ? 22 : 220, totals.profit >= 0 ? 163 : 38, totals.profit >= 0 ? 74 : 38);
        doc.text(`$${totals.profit.toLocaleString()}`, 80, currentY + 28, { align: 'right' });

        doc.setTextColor(COLOR_TEXT[0], COLOR_TEXT[1], COLOR_TEXT[2]);
        doc.text("Profit Margin", 110, currentY + 28);
        doc.text(`${totals.margin.toFixed(2)}%`, 170, currentY + 28, { align: 'right' });

        currentY += 45;

        // Monthly Trends Table
        doc.setFontSize(14);
        doc.text("Monthly Performance", 14, currentY);
        currentY += 5;

        const trendRows = trends.map(t => [
            t.name,
            `$${t.revenue.toLocaleString()}`,
            `$${t.expenses.toLocaleString()}`,
            `$${(t.revenue - t.expenses).toLocaleString()}`
        ]);

        runAutoTable(doc, {
            startY: currentY,
            head: [['Month', 'Revenue', 'Expenses', 'Net Profit']],
            body: trendRows,
            theme: 'striped',
            headStyles: { fillColor: COLOR_PRIMARY, textColor: 255 },
            columnStyles: { 1: { halign: 'right' }, 2: { halign: 'right' }, 3: { halign: 'right', fontStyle: 'bold' } }
        });

        // Expense Breakdown
        currentY = (doc as any).lastAutoTable?.finalY + 15;
        doc.text("Expense Composition", 14, currentY);
        currentY += 5;

        const expenseRows = expenseBreakdown.map(e => [
            e.name,
            `$${e.value.toLocaleString()}`,
            `${((e.value / totals.expenses) * 100).toFixed(1)}%`
        ]);

        runAutoTable(doc, {
            startY: currentY,
            head: [['Category', 'Amount', '% of Total']],
            body: expenseRows,
            theme: 'grid',
            headStyles: { fillColor: [249, 115, 22], textColor: 255 }, // Orange
            columnStyles: { 1: { halign: 'right' }, 2: { halign: 'right' } }
        });

        addFooter(doc, 1, "Confidential Financial Report");
        doc.save(`Profit_Analytics_${new Date().toISOString().slice(0,10)}.pdf`);
    } catch(e) {
        console.error(e);
        toast.error("Failed to generate analytics report.");
    }
};

// 2. Active Rentals Report
export const generateActiveRentalsPDF = (contracts: Contract[], getClientName: any, getBillboardName: any) => {
    try {
        const doc = new jsPDF();
        let currentY = addCompanyHeader(doc);

        doc.setFontSize(22);
        doc.setFont("helvetica", "bold");
        doc.text('ACTIVE RENTALS REPORT', 14, currentY);
        
        currentY += 15;

        const activeContracts = contracts.filter(c => c.status === 'Active');
        
        const rows = activeContracts.map(c => [
            getClientName(c.clientId),
            getBillboardName(c.billboardId),
            c.details,
            c.endDate,
            `$${c.monthlyRate.toLocaleString()}`
        ]);

        runAutoTable(doc, {
            startY: currentY,
            head: [['Client', 'Asset', 'Side/Slot', 'Expiring', 'Rate/Mo']],
            body: rows,
            theme: 'striped',
            headStyles: { fillColor: COLOR_PRIMARY },
            columnStyles: { 4: { halign: 'right', fontStyle: 'bold' } }
        });

        // Total Monthly
        const totalMonthly = activeContracts.reduce((sum, c) => sum + c.monthlyRate, 0);
        const finalY = (doc as any).lastAutoTable?.finalY + 10;
        
        doc.setFontSize(10);
        doc.text(`Total Monthly Recurring Revenue (MRR): $${totalMonthly.toLocaleString()}`, 14, finalY);

        addFooter(doc, 1);
        doc.save(`Active_Rentals_${new Date().toISOString().slice(0,10)}.pdf`);
    } catch(e) {
        console.error(e);
        toast.error("Failed to generate rentals report.");
    }
};

// 3. Payment Schedule Report
export const generatePaymentSchedulePDF = (schedule: any[]) => {
    try {
        const doc = new jsPDF();
        let currentY = addCompanyHeader(doc);

        doc.setFontSize(22);
        doc.setFont("helvetica", "bold");
        doc.text('SCHEDULE OF PAYMENTS', 14, currentY);
        currentY += 15;

        const rows = schedule.map(s => [
            s.clientName,
            s.date,
            s.day,
            `$${s.amount.toLocaleString()}`
        ]);

        runAutoTable(doc, {
            startY: currentY,
            head: [['Client', 'Next Due Date', 'Billing Cycle', 'Est. Amount']],
            body: rows,
            theme: 'grid',
            headStyles: { fillColor: COLOR_ACCENT }, // Orange
            columnStyles: { 3: { halign: 'right', fontStyle: 'bold' } }
        });

        addFooter(doc, 1);
        doc.save(`Payment_Schedule_${new Date().toISOString().slice(0,10)}.pdf`);
    } catch(e) { console.error(e); toast.error("Failed to generate schedule."); }
};

// 4. Received Payments History
export const generateReceivedPaymentsPDF = (receipts: Invoice[], getClientName: any) => {
    try {
        const doc = new jsPDF();
        let currentY = addCompanyHeader(doc);

        doc.setFontSize(22);
        doc.setFont("helvetica", "bold");
        doc.text('RECEIVED PAYMENTS HISTORY', 14, currentY);
        currentY += 15;

        const rows = receipts.map(r => [
            r.date,
            r.id,
            getClientName(r.clientId),
            r.paymentMethod || 'N/A',
            r.paymentReference || '-',
            `$${r.total.toLocaleString()}`
        ]);

        runAutoTable(doc, {
            startY: currentY,
            head: [['Date', 'Receipt #', 'Client', 'Method', 'Ref', 'Amount']],
            body: rows,
            theme: 'striped',
            headStyles: { fillColor: [22, 163, 74] }, // Green
            columnStyles: { 5: { halign: 'right', fontStyle: 'bold' } }
        });

        const totalReceived = receipts.reduce((sum, r) => sum + r.total, 0);
        const finalY = (doc as any).lastAutoTable?.finalY + 10;
        doc.setFontSize(10);
        doc.text(`Total Received: $${totalReceived.toLocaleString()}`, 14, finalY);

        addFooter(doc, 1);
        doc.save(`Received_Payments_${new Date().toISOString().slice(0,10)}.pdf`);
    } catch(e) { console.error(e); toast.error("Failed to generate report."); }
};

// 5. Active Clients Report
export const generateActiveClientsPDF = (clients: Client[]) => {
    try {
        const doc = new jsPDF();
        let currentY = addCompanyHeader(doc);

        doc.setFontSize(22);
        doc.setFont("helvetica", "bold");
        doc.text('ACTIVE CLIENT DIRECTORY', 14, currentY);
        currentY += 15;

        const activeClients = clients.filter(c => c.status === 'Active');
        const rows = activeClients.map(c => [
            c.companyName,
            c.contactPerson,
            c.email,
            c.phone
        ]);

        runAutoTable(doc, {
            startY: currentY,
            head: [['Company', 'Contact', 'Email', 'Phone']],
            body: rows,
            theme: 'striped',
            headStyles: { fillColor: COLOR_PRIMARY },
        });

        addFooter(doc, 1);
        doc.save(`Active_Clients_${new Date().toISOString().slice(0,10)}.pdf`);
    } catch(e) { console.error(e); toast.error("Failed to generate report."); }
};

export const generateInvoicePDF = (invoice: Invoice, client: Client, options?: PdfOutputOptions): PdfBase64 | void => {
  try {
    const doc = new jsPDF();
    let currentY = addCompanyHeader(doc);
    
    // Document Title & Info
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(COLOR_PRIMARY[0], COLOR_PRIMARY[1], COLOR_PRIMARY[2]);
    const title = invoice.type === 'Quotation' ? 'QUOTATION' : invoice.type === 'Receipt' ? 'RECEIPT' : 'INVOICE';
    doc.text(title, 14, currentY);
    
    // Status Badge logic
    const statusColor = invoice.status === 'Paid' ? [34, 197, 94] : invoice.status === 'Overdue' ? [239, 68, 68] : [249, 115, 22];
    doc.setFillColor(statusColor[0], statusColor[1], statusColor[2]);
    doc.roundedRect(pageWidth(doc) - 40, currentY - 8, 26, 8, 2, 2, 'F');
    doc.setFontSize(9);
    doc.setTextColor(255, 255, 255);
    doc.text(invoice.status.toUpperCase(), pageWidth(doc) - 27, currentY - 2.5, { align: 'center' });

    currentY += 15;

    // Info Grid
    doc.setDrawColor(230);
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(14, currentY, 182, 35, 2, 2, 'F');
    doc.setLineWidth(0.1);
    doc.rect(14, currentY, 182, 35, 'S');

    // Left: Bill To
    doc.setFontSize(8);
    doc.setTextColor(COLOR_ACCENT[0], COLOR_ACCENT[1], COLOR_ACCENT[2]);
    doc.setFont("helvetica", "bold");
    doc.text("BILL TO", 20, currentY + 8);
    
    doc.setFontSize(10);
    doc.setTextColor(COLOR_PRIMARY[0], COLOR_PRIMARY[1], COLOR_PRIMARY[2]);
    doc.text(client.companyName || 'Unknown', 20, currentY + 14);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(COLOR_TEXT_LIGHT[0], COLOR_TEXT_LIGHT[1], COLOR_TEXT_LIGHT[2]);
    doc.text(client.contactPerson, 20, currentY + 19);
    doc.text(client.email, 20, currentY + 24);

    // Right: Invoice Meta
    doc.setFontSize(8);
    doc.setTextColor(COLOR_ACCENT[0], COLOR_ACCENT[1], COLOR_ACCENT[2]);
    doc.setFont("helvetica", "bold");
    doc.text("DETAILS", 110, currentY + 8);
    
    doc.setFont("helvetica", "normal");
    doc.setTextColor(COLOR_TEXT[0], COLOR_TEXT[1], COLOR_TEXT[2]);
    
    doc.text(`Reference:`, 110, currentY + 14);
    doc.text(invoice.id, 150, currentY + 14);
    
    doc.text(`Date Issued:`, 110, currentY + 19);
    doc.text(invoice.date, 150, currentY + 19);
    
    if(invoice.contractId) {
        doc.text(`Contract:`, 110, currentY + 24);
        doc.text(invoice.contractId, 150, currentY + 24);
    } else if (invoice.contractIds && invoice.contractIds.length > 0) {
        doc.text(`Contracts:`, 110, currentY + 24);
        doc.text('Multiple (Batch)', 150, currentY + 24);
    }

    // Table
    const tableColumn = ["Description", "Amount ($)"];
    const tableRows = (invoice.items || []).map(item => [item.description, item.amount.toFixed(2)]);
    
    runAutoTable(doc, {
        startY: currentY + 45,
        head: [tableColumn],
        body: tableRows,
        theme: 'striped',
        headStyles: { fillColor: COLOR_PRIMARY, fontSize: 10, fontStyle: 'bold', textColor: 255 },
        styles: { fontSize: 10, cellPadding: 5, textColor: COLOR_TEXT },
        columnStyles: {
            1: { halign: 'right', fontStyle: 'bold' }
        },
        alternateRowStyles: { fillColor: [248, 250, 252] }
    });

    // Totals
    const finalY = (doc as any).lastAutoTable?.finalY || currentY + 60;
    const totalsX = 130;
    const valX = 195;
    
    doc.setFontSize(10);
    doc.setTextColor(COLOR_TEXT_LIGHT[0], COLOR_TEXT_LIGHT[1], COLOR_TEXT_LIGHT[2]);
    doc.text(`Subtotal:`, totalsX, finalY + 10);
    doc.text(`$${(invoice.subtotal || 0).toFixed(2)}`, valX, finalY + 10, { align: 'right' });
    
    doc.text(`VAT (15%):`, totalsX, finalY + 15);
    doc.text(`$${(invoice.vatAmount || 0).toFixed(2)}`, valX, finalY + 15, { align: 'right' });
    
    // Total Bar
    doc.setFillColor(COLOR_ACCENT[0], COLOR_ACCENT[1], COLOR_ACCENT[2]);
    doc.rect(totalsX - 5, finalY + 20, 75, 10, 'F');
    
    doc.setFontSize(12);
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.text(`Total:`, totalsX, finalY + 26.5);
    doc.text(`$${(invoice.total || 0).toFixed(2)}`, valX, finalY + 26.5, { align: 'right' });

    addFooter(doc, 1);
    return finalizePdf(doc, `${invoice.type}_${invoice.id}.pdf`, options);
  } catch (error) {
    console.error("PDF Generation Error:", error);
    if (!options?.asBase64) toast.error("Failed to generate PDF. Please check console for details.");
    return;
  }
};

export const generateMasterContractPDF = (contracts: Contract[], client: Client, billboardNameGetter: (id: string) => string) => {
    try {
        const doc = new jsPDF();
        let currentY = addCompanyHeader(doc);

        doc.setFontSize(22);
        doc.setTextColor(COLOR_PRIMARY[0], COLOR_PRIMARY[1], COLOR_PRIMARY[2]);
        doc.setFont("helvetica", "bold");
        doc.text('MASTER RENTAL AGREEMENT', 14, currentY);
        
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(COLOR_TEXT_LIGHT[0], COLOR_TEXT_LIGHT[1], COLOR_TEXT_LIGHT[2]);
        doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, currentY + 6);

        currentY += 20;

        // Parties
        doc.setFillColor(245, 245, 245);
        doc.rect(14, currentY, 182, 30, 'F');
        
        doc.setFontSize(11);
        doc.setTextColor(COLOR_PRIMARY[0], COLOR_PRIMARY[1], COLOR_PRIMARY[2]);
        doc.setFont("helvetica", "bold");
        doc.text('BETWEEN', 20, currentY + 8);
        doc.text(getCompanyProfile().name, 20, currentY + 16);
        doc.setFont("helvetica", "normal");
        doc.text("(The Lessor)", 20, currentY + 21);
        
        doc.setFont("helvetica", "bold");
        doc.text('AND', 100, currentY + 8);
        doc.text(client.companyName, 100, currentY + 16);
        doc.setFont("helvetica", "normal");
        doc.text("(The Lessee)", 100, currentY + 21);

        currentY += 40;

        // Schedule
        doc.setFontSize(12);
        doc.setTextColor(COLOR_ACCENT[0], COLOR_ACCENT[1], COLOR_ACCENT[2]);
        doc.setFont("helvetica", "bold");
        doc.text("SCHEDULE OF ASSETS", 14, currentY);
        
        const tableRows = contracts.map(c => [
            billboardNameGetter(c.billboardId),
            c.details,
            `${c.startDate} to ${c.endDate}`,
            `$${c.monthlyRate.toLocaleString()}`
        ]);

        runAutoTable(doc, {
            startY: currentY + 5,
            head: [['Billboard / Location', 'Details', 'Term', 'Monthly Rate']],
            body: tableRows,
            theme: 'grid',
            headStyles: { fillColor: COLOR_PRIMARY, textColor: 255 },
            styles: { fontSize: 9, cellPadding: 3 },
            columnStyles: { 3: { halign: 'right', fontStyle: 'bold' } }
        });

        // Totals
        const totalMonthly = contracts.reduce((acc, c) => acc + c.monthlyRate, 0);
        const totalValue = contracts.reduce((acc, c) => acc + c.totalContractValue, 0);
        
        currentY = (doc as any).lastAutoTable.finalY + 15;
        
        doc.setFontSize(10);
        doc.setTextColor(COLOR_TEXT[0], COLOR_TEXT[1], COLOR_TEXT[2]);
        doc.setFont("helvetica", "bold");
        doc.text(`Total Monthly Rental: $${totalMonthly.toLocaleString()}`, 14, currentY);
        doc.text(`Total Agreement Value: $${totalValue.toLocaleString()}`, 14, currentY + 6);

        // Terms
        currentY += 20;
        doc.setFontSize(12);
        doc.setTextColor(COLOR_ACCENT[0], COLOR_ACCENT[1], COLOR_ACCENT[2]);
        doc.text("TERMS AND CONDITIONS", 14, currentY);
        
        doc.setFontSize(9);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(COLOR_TEXT[0], COLOR_TEXT[1], COLOR_TEXT[2]);
        const terms = [
            "1. This Master Agreement covers all assets listed in the Schedule above.",
            "2. Payments are invoiced monthly in advance and are due on the 1st of each month.",
            "3. The Lessee is responsible for artwork production costs unless stated otherwise.",
            "4. The Lessor guarantees visibility and maintenance of structures.",
            "5. Early termination of any specific asset requires 30 days written notice."
        ];
        currentY += 6;
        terms.forEach(t => {
            doc.text(t, 14, currentY);
            currentY += 5;
        });

        // Signatures
        currentY += 25;
        doc.setDrawColor(150);
        doc.line(14, currentY, 90, currentY);
        doc.line(110, currentY, 186, currentY);
        
        doc.setFontSize(8);
        doc.text("Signed for Lessor", 14, currentY + 5);
        doc.text("Signed for Lessee", 110, currentY + 5);

        addFooter(doc, 1, "Master Rental Agreement");
        doc.save(`Master_Agreement_${client.companyName.replace(/\s/g, '_')}.pdf`);

    } catch (e) {
        console.error("PDF Generation Error", e);
        toast.error("Failed to generate Master Contract.");
    }
};

export const generateContractsReportPDF = (contracts: Contract[], getClientName: (id: string) => string, getBillboardName: (id: string) => string) => {
    try {
        const doc = new jsPDF();
        let currentY = addCompanyHeader(doc);

        doc.setFontSize(22);
        doc.setTextColor(COLOR_PRIMARY[0], COLOR_PRIMARY[1], COLOR_PRIMARY[2]);
        doc.setFont("helvetica", "bold");
        doc.text('CONTRACTS SUMMARY REPORT', 14, currentY);
        
        currentY += 8;
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(COLOR_TEXT_LIGHT[0], COLOR_TEXT_LIGHT[1], COLOR_TEXT_LIGHT[2]);
        doc.text(`Generated: ${new Date().toLocaleDateString()}`, 14, currentY);
        
        currentY += 15;

        const tableColumn = ["Client", "Asset", "Duration", "Monthly", "Total Value", "Status"];
        const tableRows = contracts.map(contract => [
            getClientName(contract.clientId),
            `${getBillboardName(contract.billboardId)} (${contract.details})`,
            `${contract.startDate} to ${contract.endDate}`,
            `$${contract.monthlyRate.toLocaleString()}`,
            `$${contract.totalContractValue.toLocaleString()}`,
            contract.status
        ]);

        runAutoTable(doc, {
            startY: currentY,
            head: [tableColumn],
            body: tableRows,
            theme: 'striped',
            headStyles: { fillColor: COLOR_PRIMARY, fontSize: 9, fontStyle: 'bold', textColor: 255 },
            styles: { fontSize: 8, cellPadding: 3, textColor: COLOR_TEXT },
            columnStyles: {
                3: { halign: 'right' },
                4: { halign: 'right', fontStyle: 'bold' }
            },
            alternateRowStyles: { fillColor: [248, 250, 252] }
        });

        // Summary Totals
        const totalMonthly = contracts.filter(c => c.status === 'Active').reduce((acc, c) => acc + c.monthlyRate, 0);
        const totalValue = contracts.filter(c => c.status === 'Active').reduce((acc, c) => acc + c.totalContractValue, 0);
        
        const finalY = (doc as any).lastAutoTable?.finalY || currentY + 20;
        
        if (finalY < 250) {
            doc.setFillColor(245, 247, 250);
            doc.roundedRect(14, finalY + 10, 100, 25, 2, 2, 'F');
            
            doc.setFontSize(10);
            doc.setTextColor(COLOR_TEXT[0], COLOR_TEXT[1], COLOR_TEXT[2]);
            doc.setFont("helvetica", "bold");
            doc.text("Active Contracts Summary", 20, finalY + 18);
            
            doc.setFontSize(9);
            doc.setFont("helvetica", "normal");
            doc.text(`Total Monthly Revenue: $${totalMonthly.toLocaleString()}`, 20, finalY + 25);
            doc.text(`Total Contract Value: $${totalValue.toLocaleString()}`, 20, finalY + 30);
        }

        addFooter(doc, 1);
        doc.save(`Contracts_Report_${new Date().toISOString().slice(0,10)}.pdf`);
    } catch (e) {
        console.error("Report Generation Failed", e);
        toast.error("Failed to generate contracts report.");
    }
};

export const generateContractPDF = (contract: Contract, client: Client, billboardName: string, options?: PdfOutputOptions): PdfBase64 | void => {
  try {
    const doc = new jsPDF();
    let currentY = addCompanyHeader(doc);

    doc.setFontSize(22);
    doc.setTextColor(COLOR_PRIMARY[0], COLOR_PRIMARY[1], COLOR_PRIMARY[2]);
    doc.setFont("helvetica", "bold");
    doc.text('RENTAL AGREEMENT', 14, currentY);
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(COLOR_TEXT_LIGHT[0], COLOR_TEXT_LIGHT[1], COLOR_TEXT_LIGHT[2]);
    doc.text(`Contract ID: ${contract.id}  |  Date: ${new Date().toLocaleDateString()}`, 14, currentY + 6);

    currentY += 20;

    // 1. Parties
    doc.setFillColor(245, 245, 245);
    doc.rect(14, currentY, 182, 30, 'F');
    
    doc.setFontSize(11);
    doc.setTextColor(COLOR_PRIMARY[0], COLOR_PRIMARY[1], COLOR_PRIMARY[2]);
    doc.setFont("helvetica", "bold");
    doc.text('BETWEEN', 20, currentY + 8);
    
    doc.setFontSize(10);
    doc.text(getCompanyProfile().name, 20, currentY + 16);
    doc.setFont("helvetica", "normal");
    doc.text("(The Lessor)", 20, currentY + 21);
    
    doc.setFont("helvetica", "bold");
    doc.text('AND', 100, currentY + 8);
    doc.text(client.companyName, 100, currentY + 16);
    doc.setFont("helvetica", "normal");
    doc.text("(The Lessee)", 100, currentY + 21);

    currentY += 40;

    // Sections
    const sectionTitle = (title: string, y: number) => {
        doc.setFontSize(12);
        doc.setTextColor(COLOR_ACCENT[0], COLOR_ACCENT[1], COLOR_ACCENT[2]);
        doc.setFont("helvetica", "bold");
        doc.text(title.toUpperCase(), 14, y);
        doc.setDrawColor(220);
        doc.line(14, y + 2, 196, y + 2);
    };

    sectionTitle('1. Asset & Duration', currentY);
    currentY += 10;
    
    const assetRows = [
        ['Billboard Location', billboardName],
        ['Description/Side', contract.details],
        ['Contract Start Date', contract.startDate],
        ['Contract End Date', contract.endDate],
    ];
    
    runAutoTable(doc, {
        startY: currentY,
        body: assetRows,
        theme: 'plain',
        styles: { fontSize: 10, cellPadding: 2, textColor: COLOR_TEXT },
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 60 } }
    });
    
    currentY = (doc as any).lastAutoTable.finalY + 15;
    sectionTitle('2. Financial Terms', currentY);
    currentY += 10;

    const financeRows = [
        ['Monthly Rental', `$${contract.monthlyRate.toFixed(2)}`],
        ['Installation Fee', `$${contract.installationCost.toFixed(2)}`],
        ['Production/Printing', `$${contract.printingCost.toFixed(2)}`],
        ['Total Contract Value', `$${contract.totalContractValue.toFixed(2)}`],
        ['Payment Terms', 'Invoiced monthly in advance. Due on the 1st.']
    ];

    runAutoTable(doc, {
        startY: currentY,
        body: financeRows,
        theme: 'plain',
        styles: { fontSize: 10, cellPadding: 2, textColor: COLOR_TEXT },
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 60 } }
    });

    currentY = (doc as any).lastAutoTable.finalY + 15;
    sectionTitle('3. Terms & Conditions', currentY);
    currentY += 10;

    doc.setFontSize(9);
    doc.setTextColor(COLOR_TEXT[0], COLOR_TEXT[1], COLOR_TEXT[2]);
    const terms = [
        "1. Payments are non-refundable once production has commenced.",
        "2. The Lessee is responsible for providing artwork specifications on time.",
        "3. The Lessor guarantees the visibility of the advertisement during the rental period.",
        "4. Force Majeure applies to damages caused by natural disasters.",
        "5. Early termination requires 30 days written notice and payment of remaining balance."
    ];
    terms.forEach(t => {
        doc.text(t, 14, currentY);
        currentY += 5;
    });

    currentY += 20;
    
    // Signatures
    doc.setDrawColor(150);
    doc.line(14, currentY, 90, currentY);
    doc.line(110, currentY, 186, currentY);
    
    doc.setFontSize(8);
    doc.text("Signed for Lessor", 14, currentY + 5);
    doc.text("Signed for Lessee", 110, currentY + 5);

    addFooter(doc, 1);
    return finalizePdf(doc, `Contract_${contract.id}.pdf`, options);
  } catch (error) {
    console.error("PDF Generation Error:", error);
    if (!options?.asBase64) toast.error("Failed to generate Contract PDF.");
    return;
  }
};

export const generateStatementPDF = (client: Client, transactions: Invoice[], activeRentals: Contract[], billboardNameGetter: (id: string) => string, options?: PdfOutputOptions): PdfBase64 | void => {
    try {
        const doc = new jsPDF();
        let currentY = addCompanyHeader(doc);

        doc.setFontSize(22);
        doc.setTextColor(COLOR_PRIMARY[0], COLOR_PRIMARY[1], COLOR_PRIMARY[2]);
        doc.setFont("helvetica", "bold");
        doc.text('ACCOUNT STATEMENT', 14, currentY);
        
        currentY += 8;
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(COLOR_TEXT_LIGHT[0], COLOR_TEXT_LIGHT[1], COLOR_TEXT_LIGHT[2]);
        doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, currentY);
        
        currentY += 15;

        // Client Info Box
        doc.setDrawColor(220);
        doc.setFillColor(250, 250, 250);
        doc.roundedRect(14, currentY, 100, 25, 2, 2, 'FD');
        
        doc.setFontSize(11);
        doc.setTextColor(COLOR_PRIMARY[0], COLOR_PRIMARY[1], COLOR_PRIMARY[2]);
        doc.setFont("helvetica", "bold");
        doc.text(client.companyName, 20, currentY + 8);
        
        doc.setFontSize(9);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(COLOR_TEXT[0], COLOR_TEXT[1], COLOR_TEXT[2]);
        doc.text(`Attn: ${client.contactPerson}`, 20, currentY + 14);
        doc.text(client.email, 20, currentY + 19);

        // Balance Summary Right
        const totalBilled = transactions.filter(t => t.type === 'Invoice').reduce((acc, t) => acc + t.total, 0);
        const totalPaid = transactions.filter(t => t.type === 'Receipt').reduce((acc, t) => acc + t.total, 0);
        const balance = totalBilled - totalPaid;

        const balX = 130;
        doc.setFontSize(10);
        doc.setTextColor(COLOR_TEXT_LIGHT[0], COLOR_TEXT_LIGHT[1], COLOR_TEXT_LIGHT[2]);
        doc.text("Total Invoiced:", balX, currentY + 6);
        doc.text(`$${totalBilled.toFixed(2)}`, 196, currentY + 6, { align: 'right' });
        
        doc.text("Total Paid:", balX, currentY + 12);
        doc.text(`$${totalPaid.toFixed(2)}`, 196, currentY + 12, { align: 'right' });
        
        doc.setFillColor(balance > 0 ? 254 : 240, balance > 0 ? 242 : 253, balance > 0 ? 242 : 244);
        doc.rect(balX - 2, currentY + 16, 70, 10, 'F');
        doc.setFontSize(12);
        doc.setTextColor(balance > 0 ? 220 : 22, balance > 0 ? 38 : 163, balance > 0 ? 38 : 74);
        doc.setFont("helvetica", "bold");
        doc.text("Amount Due:", balX, currentY + 23);
        doc.text(`$${balance.toFixed(2)}`, 196, currentY + 23, { align: 'right' });

        currentY += 35;

        doc.setFontSize(12);
        doc.setTextColor(COLOR_PRIMARY[0], COLOR_PRIMARY[1], COLOR_PRIMARY[2]);
        doc.text("Active Rentals", 14, currentY);
        
        const rentalRows = activeRentals.map(r => [
            billboardNameGetter(r.billboardId),
            r.details,
            `$${r.monthlyRate}/mo`,
            `${r.startDate} - ${r.endDate}`
        ]);
        
        runAutoTable(doc, {
            startY: currentY + 4,
            head: [['Billboard', 'Details', 'Rate', 'Duration']],
            body: rentalRows,
            theme: 'grid',
            headStyles: { fillColor: [241, 245, 249], textColor: COLOR_TEXT, fontStyle: 'bold' },
            styles: { fontSize: 9, textColor: COLOR_TEXT },
        });

        const finalY = (doc as any).lastAutoTable?.finalY || currentY + 20;
        doc.text("Transaction History", 14, finalY + 15);

        const transactionRows = transactions.map(t => [
            t.date,
            t.type.toUpperCase(),
            t.id,
            t.type === 'Invoice' ? `$${t.total.toFixed(2)}` : '-',
            t.type === 'Receipt' ? `$${t.total.toFixed(2)}` : '-'
        ]);

        runAutoTable(doc, {
            startY: finalY + 20,
            head: [['Date', 'Type', 'Reference', 'Billed', 'Paid']],
            body: transactionRows,
            theme: 'striped',
            headStyles: { fillColor: COLOR_PRIMARY, textColor: 255 },
            styles: { fontSize: 9, halign: 'right' },
            columnStyles: {
                0: { halign: 'left' },
                1: { halign: 'left' },
                2: { halign: 'left' }
            }
        });

        addFooter(doc, 1);
        return finalizePdf(doc, `Statement_${client.companyName.replace(/\s/g, '_')}.pdf`, options);
    } catch (error) {
        console.error("PDF Generation Error:", error);
        if (!options?.asBase64) toast.error("Failed to generate Statement PDF.");
        return;
    }
};

export const generateMaintenanceReportPDF = (billboards: Billboard[], logs: MaintenanceLog[], getStatusInfo: (id: string) => any) => {
    try {
        const doc = new jsPDF();
        let currentY = addCompanyHeader(doc);

        doc.setFontSize(22);
        doc.setTextColor(COLOR_PRIMARY[0], COLOR_PRIMARY[1], COLOR_PRIMARY[2]);
        doc.setFont("helvetica", "bold");
        doc.text('MAINTENANCE REPORT', 14, currentY);
        
        currentY += 8;
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(COLOR_TEXT_LIGHT[0], COLOR_TEXT_LIGHT[1], COLOR_TEXT_LIGHT[2]);
        doc.text(`Generated: ${new Date().toLocaleDateString()}`, 14, currentY);
        
        currentY += 15;

        // Stats Summary
        const overdue = billboards.filter(b => getStatusInfo(b.id).status === 'Overdue').length;
        const dueSoon = billboards.filter(b => getStatusInfo(b.id).status === 'Due Soon').length;
        const total = billboards.length;

        doc.setFontSize(11);
        doc.setTextColor(COLOR_TEXT[0], COLOR_TEXT[1], COLOR_TEXT[2]);
        doc.text(`Total Assets: ${total}`, 14, currentY);
        doc.text(`Overdue / Flagged: ${overdue}`, 80, currentY);
        doc.text(`Due Soon: ${dueSoon}`, 150, currentY);

        const tableRows = billboards.map(b => {
            const status = getStatusInfo(b.id);
            const lastLog = logs.filter(l => l.billboardId === b.id).sort((x,y) => new Date(y.date).getTime() - new Date(x.date).getTime())[0];
            return [
                b.name,
                `${b.location}, ${b.town}`,
                status.label,
                status.nextDue,
                lastLog ? lastLog.date : 'Never',
                lastLog ? lastLog.notes : '-'
            ];
        });

        runAutoTable(doc, {
            startY: currentY + 10,
            head: [['Asset', 'Location', 'Status', 'Next Due', 'Last Check', 'Notes']],
            body: tableRows,
            theme: 'grid',
            headStyles: { fillColor: COLOR_PRIMARY, textColor: 255, fontSize: 9 },
            styles: { fontSize: 8, cellPadding: 3 },
            columnStyles: {
                0: { fontStyle: 'bold' },
                2: { fontStyle: 'bold' }
            },
            didParseCell: function(data: any) {
                if (data.section === 'body' && data.column.index === 2) {
                    const text = data.cell.text[0];
                    if (text.includes('Overdue') || text.includes('Needs')) {
                        data.cell.styles.textColor = [220, 38, 38]; // Red
                    } else if (text.includes('Due in') || text.includes('Initial')) {
                        data.cell.styles.textColor = [245, 158, 11]; // Orange
                    } else {
                        data.cell.styles.textColor = [22, 163, 74]; // Green
                    }
                }
            }
        });

        addFooter(doc, 1, "Confidential Maintenance Report");
        doc.save(`Maintenance_Report_${new Date().toISOString().slice(0,10)}.pdf`);
    } catch(e) {
        console.error("Report Generation Failed", e);
        toast.error("Failed to generate maintenance report.");
    }
};

export const generateFeaturesPDF = () => {
    try {
        const doc = new jsPDF();
        
        // Custom Developer Header (White-labeled)
        const pageWidth = doc.internal.pageSize.width;
        doc.setFillColor(30, 41, 59); // Slate 800
        doc.rect(0, 0, pageWidth, 30, 'F');
        
        doc.setFontSize(18);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(255, 255, 255);
        doc.text("Billboard Management System", 14, 14);
        
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(203, 213, 225); // Slate 300
        doc.text("System Architecture & Specifications", 14, 20);
        
        let currentY = 45;

        doc.setFontSize(22);
        doc.setTextColor(COLOR_PRIMARY[0], COLOR_PRIMARY[1], COLOR_PRIMARY[2]);
        doc.setFont("helvetica", "bold");
        doc.text('SYSTEM CAPABILITIES', 14, currentY);
        
        currentY += 15;

        // Features List - Generic / White-label
        const features = [
            ["Feature Module", "Description of Capabilities"],
            ["Smart Dashboard & AI", "Real-time analytics, profit trends, and AI-driven business insights."],
            ["Inventory Management", "Track Static and LED assets, map view, and visibility analysis."],
            ["Rental Operations", "End-to-end contract lifecycle and automated availability checking."],
            ["Financial Suite", "Professional invoicing, expense tracking, and client statements."],
            ["Maintenance & Tasks", "Scheduled maintenance with 3-month automated cycles and logs."],
            ["Security & Data", "Role-based access control, audit logs, and cloud synchronization."]
        ];

        runAutoTable(doc, {
            startY: currentY,
            head: [features[0]],
            body: features.slice(1),
            theme: 'grid',
            headStyles: { fillColor: COLOR_ACCENT, fontSize: 11, fontStyle: 'bold', textColor: 255 },
            styles: { fontSize: 10, cellPadding: 6, valign: 'middle' },
            columnStyles: {
                0: { fontStyle: 'bold', cellWidth: 50 },
                1: { cellWidth: 'auto' }
            }
        });

        // Tech Stack Section
        const finalY = (doc as any).lastAutoTable?.finalY || currentY + 50;
        
        doc.setFontSize(14);
        doc.setTextColor(COLOR_PRIMARY[0], COLOR_PRIMARY[1], COLOR_PRIMARY[2]);
        doc.setFont("helvetica", "bold");
        doc.text('TECHNICAL STACK', 14, finalY + 15);

        const techStack = [
            ["Category", "Technology Used"],
            ["Frontend Framework", "React 18 + TypeScript + Vite"],
            ["Styling System", "Tailwind CSS (Utility-first)"],
            ["State & Storage", "Local Persistence + Neon Sync"],
            ["Mapping Engine", "Leaflet JS + OpenStreetMap"],
            ["Reporting Engine", "jsPDF + AutoTable"],
            ["AI Integration", "Google Gemini 2.5 Flash API"],
            ["Data Visualization", "Recharts"]
        ];

        runAutoTable(doc, {
            startY: finalY + 20,
            head: [techStack[0]],
            body: techStack.slice(1),
            theme: 'striped',
            headStyles: { fillColor: [71, 85, 105], fontSize: 10, fontStyle: 'bold', textColor: 255 },
            styles: { fontSize: 9, cellPadding: 4, valign: 'middle' },
            columnStyles: {
                0: { fontStyle: 'bold', cellWidth: 50 },
                1: { cellWidth: 'auto' }
            }
        });

        // Author Credit Box
        const creditY = (doc as any).lastAutoTable?.finalY || finalY + 80;
        doc.setFillColor(241, 245, 249);
        doc.rect(14, creditY + 10, 182, 25, 'F');
        doc.setDrawColor(220);
        doc.rect(14, creditY + 10, 182, 25, 'S');
        
        doc.setFontSize(9);
        doc.setTextColor(COLOR_TEXT_LIGHT[0], COLOR_TEXT_LIGHT[1], COLOR_TEXT_LIGHT[2]);
        doc.text("System Architect & Lead Developer", 20, creditY + 20);
        
        doc.setFontSize(12);
        doc.setTextColor(COLOR_ACCENT[0], COLOR_ACCENT[1], COLOR_ACCENT[2]);
        doc.setFont("helvetica", "bold");
        doc.text("Nicholas Gwanzura", 20, creditY + 28);

        // Custom Developer Footer
        const pageHeight = doc.internal.pageSize.height;
        doc.setDrawColor(230);
        doc.line(14, pageHeight - 20, pageWidth - 14, pageHeight - 20);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(`System Documentation - Generated ${new Date().toLocaleDateString()}`, 14, pageHeight - 12);
        
        doc.save('System_Features_Documentation.pdf');
    } catch (error) {
        console.error("PDF Generation Error:", error);
        toast.error("Failed to generate Features PDF.");
    }
};

export const generateCostReportPDF = (clients: Client[], printingJobs: PrintingJob[], expenses: Expense[]) => {
    try {
        const doc = new jsPDF();
        let currentY = addCompanyHeader(doc);

        doc.setFontSize(22);
        doc.setTextColor(COLOR_PRIMARY[0], COLOR_PRIMARY[1], COLOR_PRIMARY[2]);
        doc.setFont("helvetica", "bold");
        doc.text('COST & EXPENSE REPORT', 14, currentY);
        
        currentY += 8;
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(COLOR_TEXT_LIGHT[0], COLOR_TEXT_LIGHT[1], COLOR_TEXT_LIGHT[2]);
        doc.text(`Generated: ${new Date().toLocaleDateString()}`, 14, currentY);
        
        currentY += 15;

        // 1. Client Printing Spend
        doc.setFontSize(14);
        doc.setTextColor(COLOR_TEXT[0], COLOR_TEXT[1], COLOR_TEXT[2]);
        doc.setFont("helvetica", "bold");
        doc.text("Client Printing Production Analysis", 14, currentY);
        
        currentY += 5;

        const printRows = clients.map(client => {
            const jobs = printingJobs.filter(j => j.clientId === client.id);
            if (jobs.length === 0) return null;
            const totalSpent = jobs.reduce((acc, curr) => acc + curr.chargedAmount, 0);
            const totalCost = jobs.reduce((acc, curr) => acc + curr.totalCost, 0);
            const profit = totalSpent - totalCost;
            const margin = totalSpent > 0 ? ((profit / totalSpent) * 100).toFixed(1) + '%' : '0%';
            
            return [
                client.companyName,
                jobs.length.toString(),
                `$${totalSpent.toLocaleString()}`,
                `$${totalCost.toLocaleString()}`,
                `$${profit.toLocaleString()}`,
                margin
            ];
        }).filter(row => row !== null);

        runAutoTable(doc, {
            startY: currentY,
            head: [['Client', 'Jobs', 'Billed', 'Internal Cost', 'Profit', 'Margin']],
            body: printRows,
            theme: 'grid',
            headStyles: { fillColor: COLOR_PRIMARY, textColor: 255, fontSize: 9 },
            styles: { fontSize: 8, cellPadding: 3 },
            columnStyles: {
                2: { halign: 'right' },
                3: { halign: 'right' },
                4: { halign: 'right', fontStyle: 'bold' },
                5: { halign: 'right' }
            }
        });

        // 2. Operational Expenses
        currentY = (doc as any).lastAutoTable?.finalY + 15;
        doc.text("General Operational Expenses", 14, currentY);
        currentY += 5;

        const expenseRows = expenses.map(exp => [
            exp.date,
            exp.category,
            exp.description,
            exp.reference || '-',
            `$${exp.amount.toLocaleString()}`
        ]);

        runAutoTable(doc, {
            startY: currentY,
            head: [['Date', 'Category', 'Description', 'Ref', 'Amount']],
            body: expenseRows,
            theme: 'striped',
            headStyles: { fillColor: [100, 116, 139], textColor: 255, fontSize: 9 }, // Slate 500
            styles: { fontSize: 8, cellPadding: 3 },
            columnStyles: { 4: { halign: 'right', fontStyle: 'bold' } }
        });

        // Summary Box
        const totalPrintCost = printingJobs.reduce((acc, j) => acc + j.totalCost, 0);
        const totalOpsCost = expenses.reduce((acc, e) => acc + e.amount, 0);
        const totalCost = totalPrintCost + totalOpsCost;

        const finalY = (doc as any).lastAutoTable?.finalY + 15;
        doc.setFillColor(248, 250, 252);
        doc.roundedRect(14, finalY, 100, 30, 2, 2, 'F');
        doc.setDrawColor(226, 232, 240);
        doc.rect(14, finalY, 100, 30, 'S');

        doc.setFontSize(10);
        doc.setTextColor(COLOR_TEXT[0], COLOR_TEXT[1], COLOR_TEXT[2]);
        doc.setFont("helvetica", "bold");
        doc.text("Total Expense Summary", 20, finalY + 8);
        
        doc.setFontSize(9);
        doc.setFont("helvetica", "normal");
        doc.text(`Total Printing Costs: $${totalPrintCost.toLocaleString()}`, 20, finalY + 16);
        doc.text(`Total Operational Expenses: $${totalOpsCost.toLocaleString()}`, 20, finalY + 22);
        doc.setFont("helvetica", "bold");
        doc.text(`Total System Spend: $${totalCost.toLocaleString()}`, 20, finalY + 28);

        addFooter(doc, 1, "Confidential Cost Report");
        doc.save(`Cost_Report_${new Date().toISOString().slice(0,10)}.pdf`);

    } catch(e) {
        console.error("Report Generation Failed", e);
        toast.error("Failed to generate cost report.");
    }
};

const pageWidth = (doc: jsPDF) => doc.internal.pageSize.width;
